version: '3.1'
services:
  app:
    image: github.com/serinth/cab-data-researcher:latest
    environment:
      - REDIS_URI=redis:6379
      - CAB_DB_CONNECTION_STRING=root:abcd1234@tcp(mysql:3306)/ny_cab_data?charset=utf8
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0.15 # AWS RDS supports MySQL 8.0
    command: --max_allowed_packet=65011712 --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - MYSQL_DATABASE=ny_cab_data
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
