// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cabService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MedallionId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedallionId) Reset()         { *m = MedallionId{} }
func (m *MedallionId) String() string { return proto.CompactTextString(m) }
func (*MedallionId) ProtoMessage()    {}
func (*MedallionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d3c57423d4200b, []int{0}
}

func (m *MedallionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedallionId.Unmarshal(m, b)
}
func (m *MedallionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedallionId.Marshal(b, m, deterministic)
}
func (m *MedallionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedallionId.Merge(m, src)
}
func (m *MedallionId) XXX_Size() int {
	return xxx_messageInfo_MedallionId.Size(m)
}
func (m *MedallionId) XXX_DiscardUnknown() {
	xxx_messageInfo_MedallionId.DiscardUnknown(m)
}

var xxx_messageInfo_MedallionId proto.InternalMessageInfo

func (m *MedallionId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CabTripCount struct {
	Medallion            string   `protobuf:"bytes,1,opt,name=Medallion,json=medallion,proto3" json:"Medallion,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,json=count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CabTripCount) Reset()         { *m = CabTripCount{} }
func (m *CabTripCount) String() string { return proto.CompactTextString(m) }
func (*CabTripCount) ProtoMessage()    {}
func (*CabTripCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d3c57423d4200b, []int{1}
}

func (m *CabTripCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CabTripCount.Unmarshal(m, b)
}
func (m *CabTripCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CabTripCount.Marshal(b, m, deterministic)
}
func (m *CabTripCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CabTripCount.Merge(m, src)
}
func (m *CabTripCount) XXX_Size() int {
	return xxx_messageInfo_CabTripCount.Size(m)
}
func (m *CabTripCount) XXX_DiscardUnknown() {
	xxx_messageInfo_CabTripCount.DiscardUnknown(m)
}

var xxx_messageInfo_CabTripCount proto.InternalMessageInfo

func (m *CabTripCount) GetMedallion() string {
	if m != nil {
		return m.Medallion
	}
	return ""
}

func (m *CabTripCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CabTripsRequest struct {
	Medallions           []*MedallionId `protobuf:"bytes,1,rep,name=Medallions,json=medallions,proto3" json:"Medallions,omitempty"`
	SkipCache            bool           `protobuf:"varint,2,opt,name=SkipCache,json=skipCache,proto3" json:"SkipCache,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CabTripsRequest) Reset()         { *m = CabTripsRequest{} }
func (m *CabTripsRequest) String() string { return proto.CompactTextString(m) }
func (*CabTripsRequest) ProtoMessage()    {}
func (*CabTripsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d3c57423d4200b, []int{2}
}

func (m *CabTripsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CabTripsRequest.Unmarshal(m, b)
}
func (m *CabTripsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CabTripsRequest.Marshal(b, m, deterministic)
}
func (m *CabTripsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CabTripsRequest.Merge(m, src)
}
func (m *CabTripsRequest) XXX_Size() int {
	return xxx_messageInfo_CabTripsRequest.Size(m)
}
func (m *CabTripsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CabTripsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CabTripsRequest proto.InternalMessageInfo

func (m *CabTripsRequest) GetMedallions() []*MedallionId {
	if m != nil {
		return m.Medallions
	}
	return nil
}

func (m *CabTripsRequest) GetSkipCache() bool {
	if m != nil {
		return m.SkipCache
	}
	return false
}

type CabTripsResponse struct {
	Results              []*CabTripCount `protobuf:"bytes,1,rep,name=Results,json=results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CabTripsResponse) Reset()         { *m = CabTripsResponse{} }
func (m *CabTripsResponse) String() string { return proto.CompactTextString(m) }
func (*CabTripsResponse) ProtoMessage()    {}
func (*CabTripsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d3c57423d4200b, []int{3}
}

func (m *CabTripsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CabTripsResponse.Unmarshal(m, b)
}
func (m *CabTripsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CabTripsResponse.Marshal(b, m, deterministic)
}
func (m *CabTripsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CabTripsResponse.Merge(m, src)
}
func (m *CabTripsResponse) XXX_Size() int {
	return xxx_messageInfo_CabTripsResponse.Size(m)
}
func (m *CabTripsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CabTripsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CabTripsResponse proto.InternalMessageInfo

func (m *CabTripsResponse) GetResults() []*CabTripCount {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*MedallionId)(nil), "proto.MedallionId")
	proto.RegisterType((*CabTripCount)(nil), "proto.CabTripCount")
	proto.RegisterType((*CabTripsRequest)(nil), "proto.CabTripsRequest")
	proto.RegisterType((*CabTripsResponse)(nil), "proto.CabTripsResponse")
}

func init() { proto.RegisterFile("proto/cabService.proto", fileDescriptor_72d3c57423d4200b) }

var fileDescriptor_72d3c57423d4200b = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4e, 0x83, 0x40,
	0x14, 0xc6, 0x03, 0x04, 0x2b, 0xaf, 0xc6, 0x36, 0xa3, 0x56, 0xd2, 0xd4, 0x84, 0xcc, 0x8a, 0x98,
	0x58, 0x12, 0xdc, 0xb9, 0x53, 0x16, 0xa6, 0x0b, 0x37, 0x53, 0x57, 0xee, 0x06, 0x78, 0xa9, 0x13,
	0x71, 0x06, 0x99, 0xc1, 0x03, 0x78, 0x05, 0x8f, 0xe6, 0x15, 0x3c, 0x88, 0xe1, 0xaf, 0x35, 0xae,
	0x08, 0xdf, 0xfc, 0xe6, 0xfb, 0xbd, 0x97, 0x81, 0x45, 0x59, 0x29, 0xa3, 0xa2, 0x8c, 0xa7, 0x5b,
	0xac, 0xde, 0x45, 0x86, 0xeb, 0x36, 0x20, 0x6e, 0xfb, 0x59, 0xae, 0x76, 0x4a, 0xed, 0x0a, 0x8c,
	0x78, 0x29, 0x22, 0x2e, 0xa5, 0x32, 0xdc, 0x08, 0x25, 0x75, 0x07, 0xd1, 0x0b, 0x98, 0x3e, 0x60,
	0xce, 0x8b, 0x42, 0x28, 0xb9, 0xc9, 0xc9, 0x31, 0xd8, 0x9b, 0xdc, 0xb7, 0x02, 0x2b, 0xf4, 0x98,
	0x2d, 0x72, 0x7a, 0x07, 0x47, 0x09, 0x4f, 0x1f, 0x2b, 0x51, 0x26, 0xaa, 0x96, 0x86, 0xac, 0xc0,
	0x1b, 0xf1, 0x1e, 0xf3, 0x5e, 0x87, 0x80, 0x9c, 0x82, 0xdb, 0x62, 0xbe, 0x1d, 0x58, 0xa1, 0xc3,
	0xdc, 0xac, 0xf9, 0xa1, 0x19, 0xcc, 0xfa, 0x0e, 0xcd, 0xf0, 0xad, 0x46, 0x6d, 0x48, 0x0c, 0x30,
	0xd6, 0x68, 0xdf, 0x0a, 0x9c, 0x70, 0x1a, 0x93, 0x6e, 0xa2, 0xf5, 0xde, 0x38, 0x0c, 0xc6, 0x6e,
	0xdd, 0xa8, 0xb7, 0x2f, 0xa2, 0x4c, 0x78, 0xf6, 0x8c, 0xad, 0xe0, 0x90, 0x79, 0x7a, 0x08, 0xe8,
	0x2d, 0xcc, 0x7f, 0x25, 0xba, 0x54, 0x52, 0x23, 0xb9, 0x82, 0x09, 0x43, 0x5d, 0x17, 0x66, 0x50,
	0x9c, 0xf4, 0x8a, 0xfd, 0x95, 0xd8, 0xa4, 0xea, 0x98, 0x98, 0x83, 0x93, 0xf0, 0x94, 0x3c, 0xc1,
	0xfc, 0x1e, 0xcd, 0x50, 0xd6, 0xad, 0xbd, 0xf8, 0x7b, 0x71, 0xd8, 0x63, 0x79, 0xfe, 0x2f, 0xef,
	0xd4, 0xf4, 0xec, 0xe3, 0xeb, 0xfb, 0xd3, 0x9e, 0x51, 0x68, 0x9e, 0x25, 0x32, 0xcd, 0xd9, 0x8d,
	0x75, 0x99, 0x1e, 0xb4, 0xf8, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x47, 0xd3, 0x9f,
	0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CabClient is the client API for Cab service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CabClient interface {
	GetCabTripsCount(ctx context.Context, in *CabTripsRequest, opts ...grpc.CallOption) (*CabTripsResponse, error)
}

type cabClient struct {
	cc *grpc.ClientConn
}

func NewCabClient(cc *grpc.ClientConn) CabClient {
	return &cabClient{cc}
}

func (c *cabClient) GetCabTripsCount(ctx context.Context, in *CabTripsRequest, opts ...grpc.CallOption) (*CabTripsResponse, error) {
	out := new(CabTripsResponse)
	err := c.cc.Invoke(ctx, "/proto.Cab/GetCabTripsCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CabServer is the server API for Cab service.
type CabServer interface {
	GetCabTripsCount(context.Context, *CabTripsRequest) (*CabTripsResponse, error)
}

// UnimplementedCabServer can be embedded to have forward compatible implementations.
type UnimplementedCabServer struct {
}

func (*UnimplementedCabServer) GetCabTripsCount(ctx context.Context, req *CabTripsRequest) (*CabTripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCabTripsCount not implemented")
}

func RegisterCabServer(s *grpc.Server, srv CabServer) {
	s.RegisterService(&_Cab_serviceDesc, srv)
}

func _Cab_GetCabTripsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CabTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabServer).GetCabTripsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Cab/GetCabTripsCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabServer).GetCabTripsCount(ctx, req.(*CabTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cab_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Cab",
	HandlerType: (*CabServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCabTripsCount",
			Handler:    _Cab_GetCabTripsCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cabService.proto",
}
